name: copy hello.php from ActionsTest
on:
  repository_dispatch:
    types: [target-updated]
jobs:
  copy-target:
    name: copy hello.php
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: clone ActionsTest
        uses: actions/checkout@v2
        with:
          repository: satsukizzz/ActionsTest
          path: ActionsTest
          token: ${{ secrets.MY_ACCESS_TOKEN }}
      - name: copy hello.php
        run: cp ActionsTest/hello.php copied/hello.php
      - name: clean ActionsTest
        run: rm -rf ActionsTest
      - name: commit copied/hello.php
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: main
          title: 'updated hello.php'

          # Optional, but recommended
          # Defaults to "Apply automatic changes"
          commit_message: Automated Change

          # Optional. Used by `git-commit`.
          # See https://git-scm.com/docs/git-commit#_options
          commit_options: '--no-verify --signoff'

          # Optional glob pattern of files which should be added to the commit
          # Defaults to all (.)
          # See the `pathspec`-documentation for git
          # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
          # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
          file_pattern: copied/hello.php

          # Optional local file path to the repository
          # Defaults to the root of the repository
          repository: .

          # Optional commit user and author settings
          commit_user_name: My GitHub Actions Bot # defaults to "GitHub Actions"
          commit_user_email: my-github-actions-bot@example.org # defaults to "actions@github.com"
          commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run
